### ISSUE TITLE
Why does this repo install another copy of Nav2?

### ISSUE THREAD

**Issue by Russ76** [SteveMacenski/nav2_rosdevday_2021#10]
It was a surprised to find my machine compiling another stack of Nav2 after I ran Colcon Build, as per the instructions. I already had Nav2 installed in another workspace and it was sourced from my .bashrc file. Was there a test run to see if I already had it installed? It wouldn't compile properly, either. Since Cmake warnings were elevated to errors in two packages, it shut down before finishing.
By the way, my system has Jammy and Humble. Does loading the Galactic Nav2 package cause problems?
I can't run the tutorial. Gazebo looks good but Rviz doesn't load the map.
This is using my Humble version of Nav2.

**Comment by SteveMacenski** [comment]
This is a deprecated package that you can obtain more fully using the nav2 simple commander package within Nav2 itself. This is a predecessor to that package specifically for the ros dev day conference demos.

**Comment by Russ76** [comment]
I see. So it adds nothing to the Nav2 stack as a tutorial now? I'm looking for tutorials to learn more about Nav2 and get it working on my own robot. At this point it appears to be a steep learning curve. I'm using the Linorobot2 package and have the simulator mapping and driving to commanded points.
Thanks, Russ

**Comment by SteveMacenski** [comment]
The simple commander package is more or less the same as this package, but more complete. I’d look there and navigation.ros.org as well
