### ISSUE TITLE
On the topic of navigation states

### ISSUE THREAD

**Issue by miku54** [SteveMacenski/nav2_rosdevday_2021#8]
Hi Steve Macenski, if I want to write a callback function with return of def [getResult(self),](https://github.com/SteveMacenski/nav2_rosdevday_2021/blob/main/nav2_rosdevday_2021/scripts/robot_navigator.py) which topic should I subscribe to? Maybe navigate_to_pose/_action/status? But what makes me sad is that I can't find a poster for this topic.

**Comment by SteveMacenski** [comment]
Check the ROS docs on action servers, you should not go around the system by using private topics when you should have native access to it via action APIs
